#STATIC-START/friend-codex-router

location = /friend-codex-router {
    return 301 /friend-codex-router/;
}

location ^~ /friend-codex-router/ {
    root /www/wwwroot/api.leoyy.site;
    try_files $uri $uri/ =404;
    add_header Cache-Control no-cache;
}

#STATIC-END/friend-codex-router
